spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  ddl-auto: update
  show-sql: true

hnb-api:
  url: https://api.hnb.hr/tecajn-eur/v3
  cache-expiration: 3600 # jedan sat (u sekundama)


# Set the logging level for Hibernate
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE

